apiVersion: v1
kind: Service
metadata:
  name: mario-svc
  labels:
    app: mario-svc
spec:
  type: NodePort
  selector:
    app: mario-pod
  ports:
  - port: 8800
    targetPort: 8080
    nodePort: 30001

